services:
  cassandra:
    image: cassandra:5
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=dev
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=8
    healthcheck:
      test: ["CMD-SHELL","cqlsh -u cassandra -p cassandra -e 'describe cluster' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
