services:
  cass1:
    image: cassandra:5
    container_name: cass1
    environment:
      - CASSANDRA_CLUSTER_NAME=dev
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cass1
    ports: ["9042:9042"]

  cass2:
    image: cassandra:5
    container_name: cass2
    environment:
      - CASSANDRA_CLUSTER_NAME=dev
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cass1
    depends_on: [ cass1 ]

  cass3:
    image: cassandra:5
    container_name: cass3
    environment:
      - CASSANDRA_CLUSTER_NAME=dev
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cass1
    depends_on: [ cass1 ]
