version: "3.9"
services:
cassandra:
image: cassandra:5
container_name: sansa-cass-1
environment:
CASSANDRA_CLUSTER_NAME: SansaLocal
MAX_HEAP_SIZE: 1G
HEAP_NEWSIZE: 256M
ports:
- "9042:9042"
healthcheck:
test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
interval: 10s
timeout: 5s
retries: 30
cassandra-init:
image: cassandra:5
depends_on:
cassandra:
condition: service_healthy
volumes:
- ./cassandra/init.cql:/init.cql:ro
entrypoint: ["/bin/bash","-lc","cqlsh cassandra -f /init.cql && echo CQL-init-done"]
