version: '3.9'
services:
  api:
    build: .
    ports: ["8080:8080"]
    environment:
      - SANSA_ENV=dev
  cassandra:
    image: cassandra:5
    expose: ["9042"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: sansa-auth-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped