spring:
  application:
    name: sansa-auth
  jackson:
    default-property-inclusion: non_null

auth:
  jwt:
    # 32バイト以上を base64 化して格納（例はダミー）
    secretBase64: ${SANSA_AUTH_JWT_B64_SECRET:VGhpc0lzRGVtby1DaGFuZ2VNZQAAAAAAAAAAAAAAAA==}
    accessTtlSeconds: 900
    refreshTtlSeconds: 2592000
