spring:
  main:
    web-application-type: servlet

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.cassandra.CassandraHealthContributorAutoConfiguration

sansa:
  auth:
    mode: inmem

jwt:
  secret: "8511S/VeS9NcTcSnKIxQdwOMwihu0Vy7elR3rjvhvYvW60aPiUtO9yjxK0p5lGHH1sGwG8MfeyFButCh55yXeg=="
  issuer: "sansa-auth"
  accessTtl: "PT15M"    # アクセストークン有効期間 ISO-8601 例: 15分
  refreshTtl: "P7D"     # リフレッシュトークン 例: 

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    cassandra:
      enabled: false   # ★ Cassandra のヘルスチェック無効化
