spring:
  main:
    web-application-type: none

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

sansa:
  cassandra:
    contact-point: ${CASS_CONTACT_POINT:127.0.0.1}
    port: ${CASS_PORT:9042}
    datacenter: ${CASS_DC:datacenter1}
    keyspace: ${CASS_KEYSPACE:sansa_auth}

datastax-java-driver:
  basic:
    request:
      timeout: 10 seconds

app:
  mail:
    enabled: true
    transport: smtp
    from: "no-reply@sansa.space"
    # テンプレートのデフォルトロケール（必要に応じて）
    default-locale: "ja-JP"

