spring:
  main:
    web-application-type: none

sansa:
  cassandra:
    contact-point: ${CASS_CONTACT_POINT:127.0.0.1}
    port: ${CASS_PORT:9042}
    datacenter: ${CASS_DC:datacenter1}
    keyspace: ${CASS_KEYSPACE:sansa_auth}

datastax-java-driver:
  basic:
    request:
      timeout: 10 seconds
