name: sansa-auth CI

on:
  push:
    branches: [ develop ]
    paths: [ 'sansa-auth/**' ]
  pull_request:
    paths: [ 'sansa-auth/**' ]

jobs:
  it-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose_file: [ infra/docker-compose.dev.yml, infra/docker-compose.dev-3n.yml ]

    defaults:
      run:
        working-directory: sansa-auth

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Docker Compose up (${{ matrix.compose_file }})
        run: |
          docker compose -f ${{ matrix.compose_file }} up -d
          # wait for CQL port
          for i in {1..60}; do (echo > /dev/tcp/127.0.0.1/9042) >/dev/null 2>&1 && break || sleep 2; done

      - name: Run IT (cassandra profile)
        env:
          CASS_CONTACT_POINT: 127.0.0.1
          CASS_PORT: 9042
          CASS_DC: datacenter1
          CASS_KEYSPACE: sansa_auth
        run: mvn -B -ntp -Pit verify

      - name: Compose logs (on failure)
        if: failure()
        run: docker compose -f ${{ matrix.compose_file }} logs --no-color
