name: sansa-auth CI

on:
  push:
    branches: [ develop, master ]
    paths:
      - 'sansa-auth/**'
      - '.github/workflows/sansa-auth-ci.yml'
  pull_request:
    branches: [ develop, master ]
    paths:
      - 'sansa-auth/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sansa-auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B -ntp clean verify
