# .github/workflows/sansa-auth-ci.yml
name: sansa-auth CI

on:
  push:
    branches: [ develop, master ]
    paths:
      - 'sansa-auth/**'
      - '.github/workflows/sansa-auth-ci.yml'
  pull_request:
    branches: [ develop, master ]
    paths:
      - 'sansa-auth/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sansa-auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B -ntp clean test

  it-cassandra:
    name: it-cassandra
    runs-on: ubuntu-latest
    needs: build
    services:
      cassandra:
        image: cassandra:5
        ports:
          - "9042:9042"
        options: >-
          --health-cmd="cqlsh -e 'describe keyspaces' 127.0.0.1 9042"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=40
    defaults:
      run:
        working-directory: sansa-auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Cassandra は立ち上がってから安定まで少し時間がかかるので余裕を持って待機
      - name: Wait for Cassandra warm-up
        run: |
          echo "Sleeping to allow Cassandra to stabilize..."
          sleep 90

      - name: Run integration tests (profile=cassandra)
        run: mvn -B -ntp -Pit verify
